In [21]:
import numpy as np
import pandas as pd 
df=pd.read_csv("D:/luminar/Credit Score Classification Dataset.csv")
df

Age  Gender    Income            Education Marital Status   
0     25  Female   50000.0    Bachelor's Degree         Single  \
1     30    Male  100000.0      Master's Degree        Married   
2     35  Female   75000.0            Doctorate        Married   
3     40    Male  125000.0  High School Diploma         Single   
4     45  Female  100000.0    Bachelor's Degree        Married   
..   ...     ...       ...                  ...            ...   
159   29  Female   27500.0  High School Diploma         Single   
160   34    Male   47500.0   Associate's Degree         Single   
161   39  Female   62500.0    Bachelor's Degree        Married   
162   44    Male   87500.0      Master's Degree         Single   
163   49  Female   77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [22]:
df.isna().sum()

Age                   0
Gender                6
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [23]:
df.drop(['Gender'],axis=1,inplace=True)

In [24]:
df.isna().sum()

Age                   0
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [25]:
x=df['Income'].median()
df['Income'].fillna(x,inplace=True)

In [26]:
df.isna().sum()


Age                   0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [27]:
from sklearn.preprocessing import LabelEncoder
L=LabelEncoder()
df['Education']=L.fit_transform(df['Education'])
df['Marital Status']=L.fit_transform(df['Marital Status'])
df['Home Ownership']=L.fit_transform(df['Home Ownership'])


In [28]:
df

Age    Income  Education  Marital Status  Number of Children   
0     25   50000.0          1               1                   0  \
1     30  100000.0          4               0                   2   
2     35   75000.0          2               0                   1   
3     40  125000.0          3               1                   0   
4     45  100000.0          1               0                   3   
..   ...       ...        ...             ...                 ...   
159   29   27500.0          3               1                   0   
160   34   47500.0          0               1                   0   
161   39   62500.0          1               0                   2   
162   44   87500.0          4               1                   0   
163   49   77500.0          2               0                   1   

     Home Ownership Credit Score  
0                 1         High  
1                 0         High  
2                 0         High  
3                 0         High  
4                 0         High  
..              ...          ...  
159               1          Low  
160               1      Average  
161               0         High  
162               0         High  
163               0         High  

[164 rows x 7 columns]

In [29]:
x=df.iloc[:,0:6]
y=df.iloc[:,-1]

In [30]:
y

0         High
1         High
2         High
3         High
4         High
        ...   
159        Low
160    Average
161       High
162       High
163       High
Name: Credit Score, Length: 164, dtype: object

In [31]:
#train
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)

In [32]:
#pre
from sklearn.preprocessing import StandardScaler
scn=StandardScaler()
scn.fit(x_train)
x_train=scn.fit_transform(x_train)
x_test=scn.fit_transform(x_test)

In [33]:
x_train

array([[ 3.46304166e-01,  8.86470300e-01, -6.21465753e-02,
         1.09192843e+00, -7.64477485e-01, -6.93195124e-01],
       [-3.58672172e-01,  2.41353069e-01, -6.21465753e-02,
        -9.15810940e-01,  3.67346324e-01, -6.93195124e-01],
       [-9.46152454e-01,  9.67109954e-01,  1.35479534e+00,
        -9.15810940e-01,  1.49917013e+00, -6.93195124e-01],
       [ 5.81296279e-01,  3.21992723e-01,  1.35479534e+00,
         1.09192843e+00, -7.64477485e-01, -6.93195124e-01],
       [ 1.05128050e+00,  2.41353069e-01, -6.21465753e-02,
        -9.15810940e-01,  3.67346324e-01, -6.93195124e-01],
       [ 1.63876079e+00, -5.65892308e-04,  6.46324383e-01,
        -9.15810940e-01, -7.64477485e-01, -6.93195124e-01],
       [ 5.81296279e-01, -5.65892308e-04,  1.35479534e+00,
         1.09192843e+00, -7.64477485e-01, -6.93195124e-01],
       [ 1.63876079e+00,  1.37030822e+00,  6.46324383e-01,
        -9.15810940e-01, -7.64477485e-01, -6.93195124e-01],
       [ 4.63800223e-01,  5.63911685e-01,  1.354

In [40]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
k=KNeighborsClassifier()
g=GaussianNB()
s=SVC()
lst=[k,g,s]



In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
for i in lst:
    print(i)
    i.fit(x_train,y_train)
    y_pred=i.predict(x_test)

    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_pred,y_test))
    print(classification_report(y_test,y_pred))
    
    

KNeighborsClassifier()
0.92
[[ 9  2  1]
 [ 1 33  0]
 [ 0  0  4]]
              precision    recall  f1-score   support

     Average       0.75      0.90      0.82        10
        High       0.97      0.94      0.96        35
         Low       1.00      0.80      0.89         5

    accuracy                           0.92        50
   macro avg       0.91      0.88      0.89        50
weighted avg       0.93      0.92      0.92        50

GaussianNB()
0.84
[[ 9  2  5]
 [ 1 33  0]
 [ 0  0  0]]
              precision    recall  f1-score   support

     Average       0.56      0.90      0.69        10
        High       0.97      0.94      0.96        35
         Low       0.00      0.00      0.00         5

    accuracy                           0.84        50
   macro avg       0.51      0.61      0.55        50
weighted avg       0.79      0.84      0.81        50

SVC()
0.9
[[ 9  2  2]
 [ 1 33  0]
 [ 0  0  3]]
              precision    recall  f1-score   support

     Average    

c:\Users\USER01\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\USER01\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\USER01\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera